"""Initial migration

Revision ID: 9011347476bb
Revises: 
Create Date: 2026-05-25 15:57:21.226935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9011347476bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('slide_decks_item_id_idx', table_name='slide_decks')
    op.drop_index('slide_decks_user_id_idx', table_name='slide_decks')
    op.drop_table('slide_decks')
    op.drop_table('plans')
    op.drop_index('subscriptions_one_active_per_user_idx', table_name='subscriptions', postgresql_where="(status = 'active'::text)")
    op.drop_table('subscriptions')
    op.drop_index('idx_admin_broadcast_campaigns_sent_at', table_name='admin_broadcast_campaigns')
    op.drop_table('admin_broadcast_campaigns')
    op.drop_table('user_settings')
    op.drop_index('idx_user_profiles_role', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('payment_webhooks')
    op.drop_table('user_feedback')
    op.drop_index('idx_user_notifications_unread', table_name='user_notifications')
    op.drop_index('idx_user_notifications_user_created', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('idx_user_credits_balance', table_name='user_credits')
    op.drop_table('user_credits')
    op.drop_index('idx_credit_transactions_ai_log_id', table_name='credit_transactions')
    op.drop_index('idx_credit_transactions_created_at', table_name='credit_transactions')
    op.drop_index('idx_credit_transactions_payment_reference', table_name='credit_transactions')
    op.drop_index('idx_credit_transactions_user_id', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('idx_admin_banners_created_at', table_name='admin_banners')
    op.drop_table('admin_banners')
    op.drop_index('idx_auth_audit_create_at', table_name='auth_audit_logs')
    op.drop_index('idx_auth_audit_created_at', table_name='auth_audit_logs')
    op.drop_index('idx_auth_audit_email', table_name='auth_audit_logs')
    op.drop_index('idx_auth_audit_event', table_name='auth_audit_logs')
    op.drop_index('idx_auth_audit_success', table_name='auth_audit_logs')
    op.drop_table('auth_audit_logs')
    op.drop_table('payment_transactions')
    op.alter_column('ai_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_transaction_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'VND'::text"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('payment_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])", name='payment_transactions_billing_cycle_check'),
    sa.CheckConstraint("provider = ANY (ARRAY['vietqr'::text, 'momo'::text, 'zalopay'::text])", name='payment_transactions_provider_check'),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'expired'::text, 'cancelled'::text])", name='payment_transactions_status_check'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='payment_transactions_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='payment_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payment_transactions_pkey'),
    sa.UniqueConstraint('order_code', name='payment_transactions_order_code_key'),
    sa.UniqueConstraint('provider_order_id', name='payment_transactions_provider_order_id_key'),
    sa.UniqueConstraint('provider_transaction_id', name='payment_transactions_provider_transaction_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('os', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("event = ANY (ARRAY['login'::text, 'register'::text, 'logout'::text, 'password_reset'::text])", name='auth_audit_logs_event_check'),
    sa.PrimaryKeyConstraint('id', name='auth_audit_logs_pkey')
    )
    op.create_index('idx_auth_audit_success', 'auth_audit_logs', ['success'], unique=False)
    op.create_index('idx_auth_audit_event', 'auth_audit_logs', ['event'], unique=False)
    op.create_index('idx_auth_audit_email', 'auth_audit_logs', ['email'], unique=False)
    op.create_index('idx_auth_audit_created_at', 'auth_audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_auth_audit_create_at', 'auth_audit_logs', [sa.text('create_at DESC')], unique=False)
    op.create_table('admin_banners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('placement', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cta_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cta_link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('ctr', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("placement = ANY (ARRAY['Top bar'::text, 'Cạnh bên'::text, 'Popup giữa màn hình'::text])", name='admin_banners_placement_check'),
    sa.CheckConstraint("type = ANY (ARRAY['Info'::text, 'Warning'::text, 'Khuyến mãi'::text])", name='admin_banners_type_check'),
    sa.PrimaryKeyConstraint('id', name='admin_banners_pkey')
    )
    op.create_index('idx_admin_banners_created_at', 'admin_banners', [sa.text('created_at DESC')], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_log_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ai_log_id'], ['ai_logs.id'], name='credit_transactions_ai_log_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='credit_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='credit_transactions_pkey')
    )
    op.create_index('idx_credit_transactions_user_id', 'credit_transactions', ['user_id'], unique=False)
    op.create_index('idx_credit_transactions_payment_reference', 'credit_transactions', ['payment_reference'], unique=False)
    op.create_index('idx_credit_transactions_created_at', 'credit_transactions', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_credit_transactions_ai_log_id', 'credit_transactions', ['ai_log_id'], unique=False)
    op.create_table('user_credits',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_purchased', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_used', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='user_credits_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_credits_pkey')
    )
    op.create_index('idx_user_credits_balance', 'user_credits', ['balance'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("channel = ANY (ARRAY['Email'::text, 'In-app Notification'::text, 'Push Notification'::text])", name='user_notifications_channel_check'),
    sa.PrimaryKeyConstraint('id', name='user_notifications_pkey')
    )
    op.create_index('idx_user_notifications_user_created', 'user_notifications', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_user_notifications_unread', 'user_notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['new'::text, 'in_progress'::text, 'resolved'::text])", name='user_feedback_status_check'),
    sa.CheckConstraint("type = ANY (ARRAY['bug'::text, 'feature'::text, 'general'::text])", name='user_feedback_type_check'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='user_feedback_rating_check'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='user_feedback_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_feedback_pkey')
    )
    op.create_table('payment_webhooks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'received'::text"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("provider = ANY (ARRAY['vietqr'::text, 'momo'::text, 'zalopay'::text])", name='payment_webhooks_provider_check'),
    sa.CheckConstraint("status = ANY (ARRAY['received'::text, 'processed'::text, 'failed'::text])", name='payment_webhooks_status_check'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], name='payment_webhooks_transaction_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payment_webhooks_pkey')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'student'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.CheckConstraint("role = ANY (ARRAY['student'::text, 'instructor'::text, 'admin'::text])", name='user_profiles_role_check'),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='user_profiles_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    op.create_index('idx_user_profiles_role', 'user_profiles', ['role'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.TEXT(), server_default=sa.text("'light'::text"), autoincrement=False, nullable=True),
    sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), server_default=sa.text("'vi'::text"), autoincrement=False, nullable=True),
    sa.Column('receive_course_updates', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("theme = ANY (ARRAY['light'::text, 'dark'::text])", name='user_settings_theme_check'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='user_settings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_settings_pkey'),
    sa.UniqueConstraint('user_id', name='user_settings_user_id_key')
    )
    op.create_table('admin_broadcast_campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('campaign_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audience', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Đang gửi'::text"), autoincrement=False, nullable=False),
    sa.Column('open_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("audience = ANY (ARRAY['Tất cả user'::text, 'User đang hoạt động'::text, 'User trả phí (Pro/Enterprise)'::text, 'User sắp hết hạn gói'::text])", name='admin_broadcast_campaigns_audience_check'),
    sa.CheckConstraint("channel = ANY (ARRAY['Email'::text, 'In-app Notification'::text, 'Push Notification'::text])", name='admin_broadcast_campaigns_channel_check'),
    sa.CheckConstraint("status = ANY (ARRAY['Đang gửi'::text, 'Đã gửi'::text, 'Lỗi'::text])", name='admin_broadcast_campaigns_status_check'),
    sa.PrimaryKeyConstraint('id', name='admin_broadcast_campaigns_pkey')
    )
    op.create_index('idx_admin_broadcast_campaigns_sent_at', 'admin_broadcast_campaigns', [sa.text('sent_at DESC')], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])", name='subscriptions_billing_cycle_check'),
    sa.CheckConstraint("status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'pending'::text])", name='subscriptions_status_check'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], name='subscriptions_payment_transaction_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='subscriptions_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('subscriptions_one_active_per_user_idx', 'subscriptions', ['user_id'], unique=True, postgresql_where="(status = 'active'::text)")
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_monthly', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('price_yearly', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('credits_monthly', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('credits_yearly', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='plans_pkey'),
    sa.UniqueConstraint('code', name='plans_code_key')
    )
    op.create_table('slide_decks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slideshow', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mindmap_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mindmap_image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], name='slide_decks_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='slide_decks_pkey'),
    sa.UniqueConstraint('item_id', name='slide_decks_item_id_key')
    )
    op.create_index('slide_decks_user_id_idx', 'slide_decks', ['user_id'], unique=False)
    op.create_index('slide_decks_item_id_idx', 'slide_decks', ['item_id'], unique=False)
    # ### end Alembic commands ###
